variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY: https://index.docker.io/v1/
  EXTRA_OPTIONS: ''

build_base:
  image: handspiker2/ci-tools:docker 
  services:
    - docker:dind
  script:
    - docker version
    - docker build --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t handspiker2/youtube-dl:latest .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin "$DOCKER_REGISTRY"
    - docker push handspiker2/youtube-dl