steps:
- name: Fix file permissions
  image: handspiker2/ci-tools:base
  commands:
    - chmod +x docker-entrypoint.sh
  when:
    # Should always run, but linter complains if there's no event filter
    - event: [push, release, cron, manual]

# Just test build branches
- name: Build (x86_64)
  depends_on:
    - Fix file permissions
  image: woodpeckerci/plugin-docker-buildx:6
  settings:
    auto_labels: false
    build_args: "BUILD_DATE=${CI_PIPELINE_STARTED}"
    build_args_from_env: 
      - YT_DLP_VERSION
    repo: handspiker2/youtube-dl
    tags: latest
    dry_run: true
    platforms: [linux/amd64]
  when:
    - event: [push, release, cron, manual]
      branch:
        exclude:
        - master

- name: Build (arm64)
  depends_on: 
    - Fix file permissions
    - Build (x86_64)
  image: woodpeckerci/plugin-docker-buildx:6
  settings:
    auto_labels: false
    build_args: "BUILD_DATE=${CI_PIPELINE_STARTED}"
    build_args_from_env: 
      - YT_DLP_VERSION
    repo: handspiker2/youtube-dl
    tags: latest
    dry_run: true
    platforms: [linux/arm64]
  when:
    - event: [push, release, cron, manual]
      branch:
        exclude:
        - master

# Production builds
- name: Build & publish (amd64)
  depends_on: 
    - Fix file permissions
  image: woodpeckerci/plugin-docker-buildx:6
  settings:
    username:
      from_secret: docker_username
    password: 
      from_secret: docker_password
    build_args: "BUILD_DATE=${CI_PIPELINE_STARTED}"
    build_args_from_env: 
      - YT_DLP_VERSION
    repo: handspiker2/youtube-dl
    tags: latest-amd64
    dry_run: false
    platforms: [linux/amd64]
  when:
    - event: [push, release, cron, manual]
      branch:
        - master

- name: Build & publish (arm64)
  depends_on: 
    - Fix file permissions
    - Build & publish (amd64)
  image: woodpeckerci/plugin-docker-buildx:6
  settings:
    username:
      from_secret: docker_username
    password: 
      from_secret: docker_password
    build_args: "BUILD_DATE=${CI_PIPELINE_STARTED}"
    build_args_from_env: 
      - YT_DLP_VERSION
    repo: handspiker2/youtube-dl
    tags: latest-arm64
    dry_run: false
    platforms: [linux/arm64]
  when:
    - event: [push, release, cron, manual]
      branch:
        - master

- name: Combine images
  image: woodpeckerci/plugin-docker-buildx:6
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker buildx imagetools create -t handspiker2/youtube-dl:latest handspiker2/youtube-dl:latest-arm64 handspiker2/youtube-dl:latest-amd64
    - |
      if [ -n "$$YT_DLP_VERSION" ]; then
        docker buildx imagetools create -t handspiker2/youtube-dl:$$YT_DLP_VERSION handspiker2/youtube-dl:latest-arm64 handspiker2/youtube-dl:latest-amd64
      fi
  depends_on: 
    - Build & publish (amd64)
    - Build & publish (arm64)
  when:
    - event: [push, release, cron, manual]
      branch:
        - master
